---
version: '3.7'
services:
  keenetic-grafana-monitoring:
    build: .
    container_name: keenetic-grafana-monitoring
   # environment:
   #   - TZ=Europe/Kiev
    volumes:
      - ./config/config.ini:/home/config/config.ini:ro
      - ./config/metrics.json:/home/config/metrics.json:ro
    restart: always